language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.1'
      env: deps='low'
    - php: '7.1'
      env: deps='beta'

install:
  - if [[ ! $deps ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-progress --no-suggest --ansi; fi
  - if [[ $deps = 'low' ]]; then COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi
  - if [[ $deps = 'beta' ]]; then COMPOSER_MEMORY_LIMIT=-1 composer config minimum-stability beta && composer update --prefer-dist --no-progress --no-suggest --ansi; fi

script:
  - vendor/bin/phpunit --coverage-text
